version: '3.8'

services:
  # Redis - lightweight and reliable
  redis:
    image: redis:7-alpine
    container_name: av-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - av-network
    environment:
      - REDIS_REPLICATION_MODE=master

  # Redis Commander - Web UI for Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis
    networks:
      - av-network

volumes:
  redis-data:
    driver: local

networks:
  av-network:
    driver: bridge
