version: '3.8'

services:
  # Redis only - no external images needed
  redis:
    image: redis:7-alpine
    container_name: av-redis-optimized
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru", "--save", "60", "1000"]
    networks:
      - av-network

volumes:
  redis-data:
    driver: local

networks:
  av-network:
    driver: bridge
