global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: /metrics/master/prometheus
    scrape_interval: 30s

  - job_name: 'spark-worker'
    static_configs:
      - targets: ['spark-worker-1:8081']
    metrics_path: /metrics/applications/prometheus
    scrape_interval: 30s

  - job_name: 'flink-jobmanager'
    static_configs:
      - targets: ['jobmanager:8081']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'flink-taskmanager'
    static_configs:
      - targets: ['taskmanager:8081']
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: 'hdfs-namenode'
    static_configs:
      - targets: ['namenode:9870']
    metrics_path: /jmx
    scrape_interval: 30s

  - job_name: 'hdfs-datanode'
    static_configs:
      - targets: ['datanode:9864']
    metrics_path: /jmx
    scrape_interval: 30s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: /metrics
    scrape_interval: 60s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
